### ISSUE TITLE
Feature Request: Disney Plus

### ISSUE THREAD

**Issue by JamieRCHI** [unifiedremote/Remotes#138]
Are there plans to add Disney Plus Support?

**Comment by pqvst** [comment]
You could try creating a custom remote for it and submitting a PR (for example, similar to https://github.com/unifiedremote/Remotes/tree/master/Main/Netflix).

If not, if you can provide some keyboard shortcuts for actions you'd like to have, that would very helpful so that we can easily create a remote for it.

**Comment by JamieRCHI** [comment]
Thanks. I'll look into it.

**Comment by bracco23** [comment]
Hi, is anything being done for this? I was looking for this too but it doesn't seem to be introduced yet. 

I found some shortcuts at https://www.reddit.com/r/DisneyPlus/comments/d3e0kr/the_desktop_player_seems_to_be_missing_some/

that seem to be working.

While it is not done, the Netflix Web one has more or less the same shortcuts so that remote works too.

**Comment by pqvst** [comment]
We added a Disney+ remote in the latest version of the server. Download it here:
https://www.unifiedremote.com/

**Comment by JamieRCHI** [comment]
Thank you.
